export const GET_ALL_CHAT_REQUEST = "GET_ALL_CHAT_REQUEST";
export const GET_ALL_CHAT_SUCCESS = "GET_ALL_CHAT_SUCCESS";
export const GET_ALL_CHAT_FAILED = "GET_ALL_CHAT_FAILED";

export const CREATE_CHAT_REQUEST = "CREATE_CHAT_REQUEST";
export const CREATE_CHAT_SUCCESS = "CREATE_CHAT_SUCCESS";
export const CREATE_CHAT_FAILED = "CREATE_CHAT_FAILED";

export const UPDATE_CHAT_LATEST_MESSAGE = "UPDATE_CHAT_LATEST_MESSAGE";
