export const GET_ALL_FOLDER_REQUEST = "GET_ALL_FOLDER_REQUEST";
export const GET_ALL_FOLDER_SUCCESS = "GET_ALL_FOLDER_SUCCESS";
export const GET_ALL_FOLDER_FAILED = "GET_ALL_FOLDER_FAILED";

export const CREATE_FOLDER_REQUEST = "CREATE_FOLDER_REQUEST";
export const CREATE_FOLDER_SUCCESS = "CREATE_FOLDER_SUCCESS";
export const CREATE_FOLDER_FAILED = "CREATE_FOLDER_FAILED";

export const DELETE_FOLDER_REQUEST = "DELETE_FOLDER_REQUEST";
export const DELETE_FOLDER_SUCCESS = "DELETE_FOLDER_SUCCESS";
export const DELETE_FOLDER_FAILED = "DELETE_FOLDER_FAILED";

export const SHARE_FOLDER_REQUEST = "SHARE_FOLDER_REQUEST";
export const SHARE_FOLDER_SUCCESS = "SHARE_FOLDER_SUCCESS";
export const SHARE_FOLDER_FAILED = "SHARE_FOLDER_FAILED";

export const REMOVE_SHARED_FOLDER_REQUEST = "REMOVE_SHARED_FOLDER_REQUEST";
