export const GET_ALL_MESSAGE_REQUEST = "GET_ALL_MESSAGE_REQUEST";
export const GET_ALL_MESSAGE_SUCCESS = "GET_ALL_MESSAGE_SUCCESS";
export const GET_ALL_MESSAGE_FAILED = "GET_ALL_MESSAGE_FAILED";

export const CREATE_MESSAGE_REQUEST = "CREATE_MESSAGE_REQUEST";
export const CREATE_MESSAGE_SUCCESS = "CREATE_MESSAGE_SUCCESS";
export const CREATE_MESSAGE_FAILED = "CREATE_MESSAGE_FAILED";

export const GET_ALL_UNSEEN_MESSAGE_REQUEST = "GET_ALL_UNSEEN_MESSAGE_REQUEST";
export const GET_ALL_UNSEEN_MESSAGE_SUCCESS = "GET_ALL_UNSEEN_MESSAGE_SUCCESS";
export const GET_ALL_UNSEEN_MESSAGE_FAILED = "GET_ALL_UNSEEN_MESSAGE_FAILED";

export const SEENED_MESSAGE_REQUEST = "SEENED_MESSAGE_REQUEST";
export const SEENED_MESSAGE_SUCCESS = "SEENED_MESSAGE_SUCCESS";
export const SEENED_MESSAGE_FAILED = "SEENED_MESSAGE_FAILED";
