export const GET_NOTE_REQUEST = "GET_NOTE_REQUEST";
export const GET_NOTE_SUCCESS = "GET_NOTE_SUCCESS";
export const GET_NOTE_FAILED = "GET_NOTE_FAILED";

export const GET_LIKE_NOTE_REQUEST = "GET_LIKE_NOTE_REQUEST";
export const GET_LIKE_NOTE_SUCCESS = "GET_LIKE_NOTE_SUCCESS";
export const GET_LIKE_NOTE_FAILED = "GET_LIKE_NOTE_FAILED";

export const ADD_NOTE_REQUEST = "ADD_NOTE_REQUEST";
export const ADD_NOTE_SUCCESS = "ADD_NOTE_SUCCESS";
export const ADD_NOTE_FAILED = "ADD_NOTE_FAILED";

export const UPDATE_NOTE_REQUEST = "UPDATE_NOTE_REQUEST";
export const UPDATE_NOTE_SUCCESS = "UPDATE_NOTE_SUCCESS";
export const UPDATE_NOTE_FAILED = "UPDATE_NOTE_FAILED";

export const DELETE_NOTE_REQUEST = "DELETE_NOTE_REQUEST";
export const DELETE_NOTE_SUCCESS = "DELETE_NOTE_SUCCESS";
export const DELETE_NOTE_FAILED = "DELETE_NOTE_FAILED";

export const LIKE_NOTE_REQUEST = "LIKE_NOTE_REQUEST";
export const LIKE_NOTE_SUCCESS = "LIKE_NOTE_SUCCESS";
export const LIKE_NOTE_FAILED = "LIKE_NOTE_FAILED";

export const UNLIKE_NOTE_REQUEST = "UNLIKE_NOTE_REQUEST";
export const UNLIKE_NOTE_SUCCESS = "UNLIKE_NOTE_SUCCESS";
export const UNLIKE_NOTE_FAILED = "UNLIKE_NOTE_FAILED";

export const CLEAR_NOTE = "   CLEAR_NOTE";
